# Fasta To DataFrame

In [2]:
from Bio import SeqIO
import pandas as pd


In [3]:
#the whole metagenome appears to be too slow and unpractical
#doing with the sequences more than 500bp
fasta_sequences = SeqIO.parse(open("/home/andriy/canopy/scripts/metaCat/contig_idba2_step10_mt500.fasta"),'fasta')


In [4]:
#slow with the large files
cnt=0
dna=pd.DataFrame(columns=('Name', 'Sequence'))
for fasta in fasta_sequences:
    name, sequence = fasta.id, fasta.seq.tostring()
    dna.loc[cnt]=[name, sequence]
    cnt+=1
count=0
dna

Name                                           Sequence
0            contig-100_0  TGACCTCTTGCATGCCATGCAAGCGCTCTACCAGCTGAGCTAATCC...
1            contig-100_1  CGACGTCACACCTGCGTTGTGGTCGGCCGGGCTGTTCAGCGTTGTT...
2            contig-100_2  CGGCGCGCGCCGTCCGCGCGCGACGCGTAGTTCCAGCAGGTCCACT...
3            contig-100_3  CGGCAATTGTAATCGCGGAAGCCCGGACCACCGGCAAAATACACGT...
4            contig-100_4  CAAGTTGGACTGCACCAGAACATCAACTATCCCGATCACGAAGACG...
5            contig-100_5  CGGCCAGCACTTCGATCCGGCGGCCGTCGATGGTCAACATGCTGCC...
6            contig-100_6  GACGCAGCTCATCGGGTCCTGCGTCGCGCGCAGCGTCTCCTCGAGC...
7            contig-100_7  CAGGGTAAGAAAATAGCTGGCGCGATTCGCGGGATTGCAATTTCGA...
8            contig-100_8  GAGCATGGGGAAACGCCGTGCAACGGCGAAAATCGAAATGCGTATG...
9            contig-100_9  TGACGGTCACCGGCGCGACGCTCTGCAAACGCTTTTCGGTCACTTG...
10          contig-100_10  ATGATGAGGAGCGAATCCGGCGTTGCCTAACCTACTGCGACTCGCC...
11          contig-100_11  GTGAGCGAGGCGCTCTGGCTATCTGTGCGGACAAGCATCCTCGCGG...
12          contig-100_12  GCGTACCTCCCAGGTGTAAGCAATCAAGGAGTTACGCCACTTTTAT...
13          contig-100_13  GGTCCCATGAGCGCTCTTTCGGCGCCTCCAGGCCCCGGTAAGATCT...
14          contig-100_14  GCCGGCCGGCGAGCTGCGCGCGCTTTCCGCAGCATCGTTGTAATCT...
15          contig-100_15  AGCGTCGCGAACGCGCCCCACATGTAGCCGAAGCCGAAGCCGGTCG...
16          contig-100_16  GCAGCGCGCCGCGCGCGGCACGGAGAAGCGAGCTGCGCACAAGGCT...
17          contig-100_17  AGTACCTTGAGACGCTTGCCCTCGAAGAGCATCCAAGCACCCGGCC...
18          contig-100_18  TTTCTCAGCTTATCTAGCACGTCGACACTCGTCTCACCATCCCCAA...
19          contig-100_19  GCGCCAGCGCCGGCTTCAGGAGGACCGGAAGATGATCCATACGCGC...
20          contig-100_20  TTGAAGTCGACGCTGATCGGTTCTTGCTGGCGCTGCCACCACAAGA...
21          contig-100_21  AAATCGTAGAAGTCGCCTCCGACGGCCCTGGCCGGCTGGAAGGAAA...
22          contig-100_22  GCGAGGCCGCTCGTGAACATGTGGTGCGCCCAAACCATGAAGGATA...
23          contig-100_23  GAATGCCGGTGGCCGCCGCTTTCATCCTTACTCCAATGACCCATCT...
24          contig-100_24  GTGCCGAGCGGTAGCGCCGCGTCGATGATTTGCAACTGCCGGCTCA...
25          contig-100_25  GCAGATGCGCGCGCTCGAAAGCGGGCGCTGGATCGTGCGGAGAGCC...
26          contig-100_26  TACGACGATCTGGGTTCGGCGCTCTTCGACGCGATCACGGCGCTTC...
27          contig-100_27  CGAATGATCATCGCCGCGCGCTCGACCTCGTTCAGATCGTCCGATT...
28          contig-100_28  GGCCCTGCTCCTGTTGGCCCTGCTCCTGTTGGCCCTGCTCATCATC...
29          contig-100_29  GCGGTGTAGGCGTCGCAGCCTGGGCTGCGGCGGGTGCCTCGGCCGT...
...                   ...                                                ...
103556  contig-100_103556  TCTCGGTAGGGGCAGCAATTCATTGCGCCCAAAGATGGGGTGGCGG...
103557  contig-100_103557  TGGCGCTGCTCGCGCTGACCTCCCAGGTGATCGGCTGGCTGCTCAT...
103558  contig-100_103558  GCCGCGCAGCCCGCTCGGCGAATTGCATCATCAGCACCGCGCCGAT...
103559  contig-100_103559  TGGAAGCCGTCGCCGCTGATATATTCTGGATGCGCTGTTAGCTCGC...
103560  contig-100_103560  CCCAAAATTTTGCAATGAGTGATAATTTTTTTGGATCCACATTTGG...
103561  contig-100_103561  CAGCCGGATTGCCGGATAACGGCCACCATGTCGCTGATTATCTGCC...
103562  contig-100_103562  GTCCGGCGGGACCGGCCCCGCCGCGTCGAGCGACACAGCGCCCGCG...
103563  contig-100_103563  TGAGCGCCTCGAGGTCGCGGCGGCCTTCGTTGGTGGCGAAGATAGC...
103564  contig-100_103564  AGCTGACCGCGAAGGCGCTCTGCGCAGTGTCCTGCTGCTTGCTCTG...
103565  contig-100_103565  GAGTTGAGCGATCCTTTAAACTTACGACGCTAAGCATCTTTGGTTT...
103566  contig-100_103566  CGGCGGCGGACGCCAGGCCGTCGAGATCGGTCAGCAGCAGGTTGCC...
103567  contig-100_103567  TCCGAGTACAGGCCCTCTCTGATTGTAGGCCCTCTCTGATTGAATG...
103568  contig-100_103568  ACACGTTGTCTATGTTTGGGTAGTGTGTTTACTGGCATAGCTTCAG...
103569  contig-100_103569  GACGGCCCGCAGGTAGTCGATCAGCCTTTGCCCGGGTAGTCCCCGG...
103570  contig-100_103570  ACCTTACAGCTTTTAGCGCGTGCATCTCTAAATGATAAAGACTTAT...
103571  contig-100_103571  GACCCGGACCATGAAGAATTCGTCGAGGCTGCTGCTCACAATTGCC...
103572  contig-100_103572  TTCCCAAGGATACTCGAGACATCATCCTGCAGTACCACGGCACGTA...
103573  contig-100_103573  GATGACTGCGCTGGGCATCGCGCTCACCGTTACGACCGCGATCTTT...
103574  contig-100_103574  CTCCTCGAACGCATCAAGGCAGCAGAAGAAGCCAAACAAGGCTAGA...
103575  contig-100_103575  GCGGCGCCGAACTCCCGGTAACAGGGGAAGATCCAGTCCCCCTCGC...
103576  contig-10

In [8]:
import khmer

In [ ]:
def dna2kmer(seq):
    ktable = khmer.new_ktable(6)
    ktable.consume(seq)
    

In [5]:
#fast
k=6
dna['encoded']=dna['Sequence'].apply(lambda x: " ".join([x[i:i+k] for i in range(len(x)-k+1)]))
dna

Name                                           Sequence  \
0            contig-100_0  TGACCTCTTGCATGCCATGCAAGCGCTCTACCAGCTGAGCTAATCC...   
1            contig-100_1  CGACGTCACACCTGCGTTGTGGTCGGCCGGGCTGTTCAGCGTTGTT...   
2            contig-100_2  CGGCGCGCGCCGTCCGCGCGCGACGCGTAGTTCCAGCAGGTCCACT...   
3            contig-100_3  CGGCAATTGTAATCGCGGAAGCCCGGACCACCGGCAAAATACACGT...   
4            contig-100_4  CAAGTTGGACTGCACCAGAACATCAACTATCCCGATCACGAAGACG...   
5            contig-100_5  CGGCCAGCACTTCGATCCGGCGGCCGTCGATGGTCAACATGCTGCC...   
6            contig-100_6  GACGCAGCTCATCGGGTCCTGCGTCGCGCGCAGCGTCTCCTCGAGC...   
7            contig-100_7  CAGGGTAAGAAAATAGCTGGCGCGATTCGCGGGATTGCAATTTCGA...   
8            contig-100_8  GAGCATGGGGAAACGCCGTGCAACGGCGAAAATCGAAATGCGTATG...   
9            contig-100_9  TGACGGTCACCGGCGCGACGCTCTGCAAACGCTTTTCGGTCACTTG...   
10          contig-100_10  ATGATGAGGAGCGAATCCGGCGTTGCCTAACCTACTGCGACTCGCC...   
11          contig-100_11  GTGAGCGAGGCGCTCTGGCTATCTGTGCGGACAAGCATCCTCGCGG...   
12          contig-100_12  GCGTACCTCCCAGGTGTAAGCAATCAAGGAGTTACGCCACTTTTAT...   
13          contig-100_13  GGTCCCATGAGCGCTCTTTCGGCGCCTCCAGGCCCCGGTAAGATCT...   
14          contig-100_14  GCCGGCCGGCGAGCTGCGCGCGCTTTCCGCAGCATCGTTGTAATCT...   
15          contig-100_15  AGCGTCGCGAACGCGCCCCACATGTAGCCGAAGCCGAAGCCGGTCG...   
16          contig-100_16  GCAGCGCGCCGCGCGCGGCACGGAGAAGCGAGCTGCGCACAAGGCT...   
17          contig-100_17  AGTACCTTGAGACGCTTGCCCTCGAAGAGCATCCAAGCACCCGGCC...   
18          contig-100_18  TTTCTCAGCTTATCTAGCACGTCGACACTCGTCTCACCATCCCCAA...   
19          contig-100_19  GCGCCAGCGCCGGCTTCAGGAGGACCGGAAGATGATCCATACGCGC...   
20          contig-100_20  TTGAAGTCGACGCTGATCGGTTCTTGCTGGCGCTGCCACCACAAGA...   
21          contig-100_21  AAATCGTAGAAGTCGCCTCCGACGGCCCTGGCCGGCTGGAAGGAAA...   
22          contig-100_22  GCGAGGCCGCTCGTGAACATGTGGTGCGCCCAAACCATGAAGGATA...   
23          contig-100_23  GAATGCCGGTGGCCGCCGCTTTCATCCTTACTCCAATGACCCATCT...   
24          contig-100_24  GTGCCGAGCGGTAGCGCCGCGTCGATGATTTGCAACTGCCGGCTCA...   
25          contig-100_25  GCAGATGCGCGCGCTCGAAAGCGGGCGCTGGATCGTGCGGAGAGCC...   
26          contig-100_26  TACGACGATCTGGGTTCGGCGCTCTTCGACGCGATCACGGCGCTTC...   
27          contig-100_27  CGAATGATCATCGCCGCGCGCTCGACCTCGTTCAGATCGTCCGATT...   
28          contig-100_28  GGCCCTGCTCCTGTTGGCCCTGCTCCTGTTGGCCCTGCTCATCATC...   
29          contig-100_29  GCGGTGTAGGCGTCGCAGCCTGGGCTGCGGCGGGTGCCTCGGCCGT...   
...                   ...                                                ...   
103556  contig-100_103556  TCTCGGTAGGGGCAGCAATTCATTGCGCCCAAAGATGGGGTGGCGG...   
103557  contig-100_103557  TGGCGCTGCTCGCGCTGACCTCCCAGGTGATCGGCTGGCTGCTCAT...   
103558  contig-100_103558  GCCGCGCAGCCCGCTCGGCGAATTGCATCATCAGCACCGCGCCGAT...   
103559  contig-100_103559  TGGAAGCCGTCGCCGCTGATATATTCTGGATGCGCTGTTAGCTCGC...   
103560  contig-100_103560  CCCAAAATTTTGCAATGAGTGATAATTTTTTTGGATCCACATTTGG...   
103561  contig-100_103561  CAGCCGGATTGCCGGATAACGGCCACCATGTCGCTGATTATCTGCC...   
103562  contig-100_103562  GTCCGGCGGGACCGGCCCCGCCGCGTCGAGCGACACAGCGCCCGCG...   
103563  contig-100_103563  TGAGCGCCTCGAGGTCGCGGCGGCCTTCGTTGGTGGCGAAGATAGC...   
103564  contig-100_103564  AGCTGACCGCGAAGGCGCTCTGCGCAGTGTCCTGCTGCTTGCTCTG...   
103565  contig-100_103565  GAGTTGAGCGATCCTTTAAACTTACGACGCTAAGCATCTTTGGTTT...   
103566  contig-100_103566  CGGCGGCGGACGCCAGGCCGTCGAGATCGGTCAGCAGCAGGTTGCC...   
103567  contig-100_103567  TCCGAGTACAGGCCCTCTCTGATTGTAGGCCCTCTCTGATTGAATG...   
103568  contig-100_103568  ACACGTTGTCTATGTTTGGGTAGTGTGTTTACTGGCATAGCTTCAG...   
103569  contig-100_103569  GACGGCCCGCAGGTAGTCGATCAGCCTTTGCCCGGGTAGTCCCCGG...   
103570  contig-100_103570  ACCTTACAGCTTTTAGCGCGTGCATCTCTAAATGATAAAGACTTAT...   
103571  contig-100_103571  GACCCGGACCATGAAGAATTCGTCGAGGCTGCTGCTCACAATTGCC...   
103572  contig-100_103572  TTCCCAAGGATACTCGAGACATCATCCTGCAGTACCACGGCACGTA...   
103573  contig-100_103573  GATGACTGCGCTGGGCATCGCGCTCACCGTTACGACCGCGATCTTT...   
103574  contig-100_10

In [6]:
import numpy as np
import graphlab
from scipy.sparse import csr_matrix
from sklearn.metrics.pairwise import pairwise_distances
import time
from copy import copy
import matplotlib.pyplot as plt
%matplotlib inline

'''Check GraphLab Create version'''
from distutils.version import StrictVersion
assert (StrictVersion(graphlab.version) >= StrictVersion('1.8.5')), 'GraphLab Create must be version 1.8.5 or later.'

'''compute norm of a sparse vector
   Thanks to: Jaiyam Sharma'''
def norm(x):
    sum_sq=x.dot(x.T)
    norm=np.sqrt(sum_sq)
    return(norm)

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: /tmp/graphlab_server_1489344789.log
INFO:graphlab.cython.cy_server:GraphLab Create v2.1 st

This non-commercial license of GraphLab Create for academic use is assigned to andriy.sheremet@ucalgary.ca and will expire on November 15, 2017.


In [7]:
gl_dna=graphlab.SFrame(dna)
gl_dna=gl_dna.add_row_number()
gl_dna

Columns:
	id	int
	Name	str
	Sequence	str
	encoded	str

Rows: 103586

Data:
+----+--------------+-------------------------------+
| id |     Name     |            Sequence           |
+----+--------------+-------------------------------+
| 0  | contig-100_0 | TGACCTCTTGCATGCCATGCAAGCGC... |
| 1  | contig-100_1 | CGACGTCACACCTGCGTTGTGGTCGG... |
| 2  | contig-100_2 | CGGCGCGCGCCGTCCGCGCGCGACGC... |
| 3  | contig-100_3 | CGGCAATTGTAATCGCGGAAGCCCGG... |
| 4  | contig-100_4 | CAAGTTGGACTGCACCAGAACATCAA... |
| 5  | contig-100_5 | CGGCCAGCACTTCGATCCGGCGGCCG... |
| 6  | contig-100_6 | GACGCAGCTCATCGGGTCCTGCGTCG... |
| 7  | contig-100_7 | CAGGGTAAGAAAATAGCTGGCGCGAT... |
| 8  | contig-100_8 | GAGCATGGGGAAACGCCGTGCAACGG... |
| 9  | contig-100_9 | TGACGGTCACCGGCGCGACGCTCTGC... |
+----+--------------+-------------------------------+
+-------------------------------+
|            encoded            |
+-------------------------------+
| TGACCT GACCTC ACCTCT CCTCT... |
| CGACGT GACGTC ACGTCA CGTCA... |
| CGGCGC GGCGCG GCGCGC CGCGC... |
| CGGCAA GGCAAT GCAATT CAATT... |
| CAAGTT AAGTTG AGTTGG GTTGG... |
| CGGCCA GGCCAG GCCAGC CCAGC... |
| GACGCA ACGCAG CGCAGC GCAGC... |
| CAGGGT AGGGTA GGGTAA GGTAA... |
| GAGCAT AGCATG GCATGG CATGG... |
| TGACGG GACGGT ACGGTC CGGTC... |
+-------------------------------+
[103586 rows x 4 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [242]:
#del dna

In [8]:
gl_dna['tf_idf'] = graphlab.text_analytics.tf_idf(gl_dna['encoded'])
gl_dna

Columns:
	id	int
	Name	str
	Sequence	str
	encoded	str
	tf_idf	dict

Rows: 103586

Data:
+----+--------------+-------------------------------+
| id |     Name     |            Sequence           |
+----+--------------+-------------------------------+
| 0  | contig-100_0 | TGACCTCTTGCATGCCATGCAAGCGC... |
| 1  | contig-100_1 | CGACGTCACACCTGCGTTGTGGTCGG... |
| 2  | contig-100_2 | CGGCGCGCGCCGTCCGCGCGCGACGC... |
| 3  | contig-100_3 | CGGCAATTGTAATCGCGGAAGCCCGG... |
| 4  | contig-100_4 | CAAGTTGGACTGCACCAGAACATCAA... |
| 5  | contig-100_5 | CGGCCAGCACTTCGATCCGGCGGCCG... |
| 6  | contig-100_6 | GACGCAGCTCATCGGGTCCTGCGTCG... |
| 7  | contig-100_7 | CAGGGTAAGAAAATAGCTGGCGCGAT... |
| 8  | contig-100_8 | GAGCATGGGGAAACGCCGTGCAACGG... |
| 9  | contig-100_9 | TGACGGTCACCGGCGCGACGCTCTGC... |
+----+--------------+-------------------------------+
+-------------------------------+-------------------------------+
|            encoded            |             tf_idf            |
+-------------------------------+-------------------------------+
| TGACCT GACCTC ACCTCT CCTCT... | {'gcagag': 59.766830051857... |
| CGACGT GACGTC ACGTCA CGTCA... | {'gcagag': 43.164932815230... |
| CGGCGC GGCGCG GCGCGC CGCGC... | {'gcagag': 36.524173920579... |
| CGGCAA GGCAAT GCAATT CAATT... | {'gcagag': 23.242656131278... |
| CAAGTT AAGTTG AGTTGG GTTGG... | {'gcagag': 16.601897236627... |
| CGGCCA GGCCAG GCCAGC CCAGC... | {'gcagag': 29.883415025928... |
| GACGCA ACGCAG CGCAGC GCAGC... | {'gcagag': 33.203794473254... |
| CAGGGT AGGGTA GGGTAA GGTAA... | {'gcagag': 24.902845854940... |
| GAGCAT AGCATG GCATGG CATGG... | {'gcagag': 34.863984196917... |
| TGACGG GACGGT ACGGTC CGGTC... | {'gcagag': 23.242656131278... |
+-------------------------------+-------------------------------+
[103586 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [9]:
def sframe_to_scipy(column):
    """ 
    Convert a dict-typed SArray into a SciPy sparse matrix.
    
    Returns
    -------
        mat : a SciPy sparse matrix where mat[i, j] is the value of word j for document i.
        mapping : a dictionary where mapping[j] is the word whose values are in column j.
    """
    # Create triples of (row_id, feature_id, count).
    x = graphlab.SFrame({'X1':column})
    
    # 1. Add a row number.
    x = x.add_row_number()
    # 2. Stack will transform x to have a row for each unique (row, key) pair.
    x = x.stack('X1', ['feature', 'value'])

    # Map words into integers using a OneHotEncoder feature transformation.
    f = graphlab.feature_engineering.OneHotEncoder(features=['feature'])

    # We first fit the transformer using the above data.
    f.fit(x)

    # The transform method will add a new column that is the transformed version
    # of the 'word' column.
    x = f.transform(x)

    # Get the feature mapping.
    mapping = f['feature_encoding']

    # Get the actual word id.
    x['feature_id'] = x['encoded_features'].dict_keys().apply(lambda x: x[0])

    # Create numpy arrays that contain the data for the sparse matrix.
    i = np.array(x['id'])
    j = np.array(x['feature_id'])
    v = np.array(x['value'])
    width = x['id'].max() + 1
    height = x['feature_id'].max() + 1

    # Create a sparse matrix.
    mat = csr_matrix((v, (i, j)), shape=(width, height))

    return mat, mapping

In [ ]:
start=time.time()
corpus, mapping = sframe_to_scipy(gl_dna['tf_idf'])
end=time.time()
print end-start

In [39]:
corpus.shape

(1955, 4096)

In [40]:
mapping.shape

(4096, 3)

In [44]:
len(mapping)

4096

In [42]:
def generate_random_vectors(num_vector, dim):
    return np.random.randn(dim, num_vector)

In [174]:
# Generate 3 random vectors of dimension 5, arranged into a single 5 x 3 matrix.
np.random.seed(0) # set seed=0 for consistent results
generate_random_vectors(num_vector=8, dim=5)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351,  0.76103773,
         0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982,
         0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
         1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897,  1.23029068,
         1.20237985, -0.38732682, -0.30230275]])

In [189]:
# Generate 16 random vectors of dimension 547979
np.random.seed(0)
random_vectors = generate_random_vectors(num_vector=8, dim=len(mapping))
random_vectors.shape

(4096, 8)

In [190]:
doc = corpus[0, :] # vector of tf-idf values for document 0
doc.dot(random_vectors[:, 0]) >= 0 # True if positive sign; False if negative sign

array([False], dtype=bool)

In [191]:
doc

<1x4096 sparse matrix of type '<type 'numpy.float64'>'
	with 471 stored elements in Compressed Sparse Row format>

In [192]:
doc.dot(random_vectors[:, 2]) >= 0 # True if positive sign; False if negative sign

array([False], dtype=bool)

In [193]:
doc.dot(random_vectors) >= 0 # should return an array of 16 True/False bits

array([[False,  True, False, False,  True,  True,  True, False]], dtype=bool)

In [194]:
np.array(doc.dot(random_vectors) >= 0, dtype=int) # display index bits in 0/1's

array([[0, 1, 0, 0, 1, 1, 1, 0]])

In [195]:
corpus[0:2].dot(random_vectors) >= 0 # compute bit indices of first two documents

array([[False,  True, False, False,  True,  True,  True, False],
       [False, False, False, False,  True,  True, False,  True]], dtype=bool)

In [196]:
corpus.dot(random_vectors) >= 0 # compute bit indices of ALL documents

array([[False,  True, False, ...,  True,  True, False],
       [False, False, False, ...,  True, False,  True],
       [ True,  True,  True, ..., False, False,  True],
       ..., 
       [False,  True, False, ...,  True,  True, False],
       [ True, False, False, ...,  True,  True, False],
       [ True,  True,  True, ..., False, False, False]], dtype=bool)

In [197]:
doc = corpus[0, :]  # first document
index_bits = (doc.dot(random_vectors) >= 0)
powers_of_two = (1 << np.arange(7, -1, -1))
print index_bits
print powers_of_two
print index_bits.dot(powers_of_two)

[[False  True False False  True  True  True False]]
[128  64  32  16   8   4   2   1]
[78]


In [198]:
index_bits = corpus.dot(random_vectors) >= 0
index_bits.dot(powers_of_two)

array([ 78,  13, 225, ...,  78, 158, 232])

In [199]:
lst = list(index_bits.dot(powers_of_two))
new_dct={}
for i in lst:
    if i not in new_dct.keys():
        new_dct[i]=lst.count(i)

In [200]:
sum(new_dct.values())

1955

In [201]:
def train_lsh(data, num_vector=8, seed=None):
    
    dim = data.shape[1]
    if seed is not None:
        np.random.seed(seed)
    random_vectors = generate_random_vectors(num_vector, dim)
  
    powers_of_two = 1 << np.arange(num_vector-1, -1, -1)
  
    table = {}
    
    # Partition data points into bins
    bin_index_bits = (data.dot(random_vectors) >= 0)
  
    # Encode bin index bits into integers
    bin_indices = bin_index_bits.dot(powers_of_two)
    
    # Update `table` so that `table[i]` is the list of document ids with bin index equal to i.
    for data_index, bin_index in enumerate(bin_indices):
        if bin_index not in table:
            # If no list yet exists for this bin, assign the bin an empty list.
            table[bin_index] = [] # YOUR CODE HERE
        # Fetch the list of document ids associated with the bin and add the document id to the end.
        table[bin_index].append(data_index) # YOUR CODE HERE

    model = {'data': data,
             'bin_index_bits': bin_index_bits,
             'bin_indices': bin_indices,
             'table': table,
             'random_vectors': random_vectors,
             'num_vector': num_vector}
    
    return model

In [202]:
lst=np.array([1, 2,3, 1, 4, 1, 5])
lst==1

array([ True, False, False,  True, False,  True, False], dtype=bool)

In [203]:
model = train_lsh(corpus, num_vector=8, seed=143)
table = model['table']
if   0 in table and table[0]   == [39583] and \
   143 in table and table[143] == [19693, 28277, 29776, 30399]:
    print 'Passed!'
else:
    print 'Check your code.'

Check your code.


In [204]:
table

{0: [58, 902, 1016, 1517],
 1: [159, 657, 1729, 1752],
 2: [209, 1147, 1168, 1313, 1884],
 3: [35, 411, 570, 580, 917, 1622, 1671, 1739],
 4: [882, 996, 1480],
 5: [1050, 1759, 1767],
 6: [274, 313, 387, 1433, 1925],
 7: [94, 103],
 8: [221, 742, 1617, 1709, 1880, 1900],
 9: [390, 462, 556, 644, 1141, 1278, 1286],
 10: [310, 708, 939, 1159, 1265],
 11: [114, 320, 350, 649, 823, 945, 1412, 1578],
 12: [19, 1425],
 13: [208, 232, 483, 777, 804, 852, 1271, 1283, 1302, 1912],
 14: [193, 357],
 15: [1245],
 16: [5,
  101,
  120,
  283,
  300,
  332,
  604,
  668,
  815,
  829,
  910,
  1205,
  1330,
  1382,
  1914,
  1952],
 17: [248,
  303,
  337,
  522,
  571,
  844,
  1176,
  1273,
  1387,
  1388,
  1419,
  1423,
  1513,
  1559,
  1629,
  1806],
 18: [195, 236, 490, 904, 982, 1061, 1303, 1347, 1486, 1846],
 19: [17,
  129,
  144,
  343,
  434,
  439,
  517,
  593,
  594,
  795,
  807,
  840,
  867,
  888,
  890,
  1030,
  1109,
  1183,
  1420,
  1426,
  1453,
  1528,
  1530,
  1565,
  15

In [205]:
item='Ga0073928_11058481'
gl_dna[gl_dna['Name'] == item]

Columns:
	id	int
	Name	str
	Sequence	str
	encoded	str
	tf_idf	dict

Rows: Unknown

Data:
+----+--------------------+-------------------------------+
| id |        Name        |            Sequence           |
+----+--------------------+-------------------------------+
| 18 | Ga0073928_11058481 | CGTCGATTCGAAATCGGTCGTCGTGA... |
+----+--------------------+-------------------------------+
+-------------------------------+-------------------------------+
|            encoded            |             tf_idf            |
+-------------------------------+-------------------------------+
| CGTCGA GTCGAT TCGATT CGATT... | {'cgtcga': 0.7858010449486... |
+-------------------------------+-------------------------------+
[? rows x 5 columns]
Note: Only the head of the SFrame is printed. This SFrame is lazily evaluated.
You can use sf.materialize() to force materialization.

In [206]:
test_id=gl_dna[gl_dna['Name'] == item]['id'][0]
test_id

18

In [207]:
for i, j in table.items():
    if test_id in j:
        test_bin = i
test_bin

81

In [208]:
table[test_bin]

[9,
 18,
 88,
 91,
 128,
 138,
 197,
 340,
 376,
 527,
 553,
 581,
 601,
 734,
 849,
 1044,
 1059,
 1102,
 1130,
 1266,
 1428,
 1472,
 1686,
 1851]

In [128]:
#46524: [1162, 1793, 1805],

In [211]:
test9=gl_dna[9]

In [212]:
test18=gl_dna[18]

In [103]:
gl_dna[1805]['Sequence']

'CACTGGTTTCGAGCGAGCAGCGTGCATTGACGGACTACGCGCAGATCGGCGAGACCGCCGCGGAACTCAAACGGTACGCGAAATCGATCGGGGGTTCGGTCTACGTGAAAGACAAACGCCGCCAATGATTCGCAAACTGGTCGCGATCGCGCTCTTGTTCGCTTTCGTTCCGGCCGTCGCATTGCCGTCGGGCTTGACCGCAAAGATCCAAGCCGAACGCCGCAAGAAAGAGGCGCTCGACCGTCAGCTCCACCAAAAGCGGGTGGAGCTCCACACTGCGACGGTGCGCGTCATGAATCTGCAAGGCGCGCTCGATCAAACCAACCACTCGATCCACGACGTTTCCTCGCGGCTCGATGCAATCACCGGGCAGCAGGCGAGTACGCAACGCAAACTTGCATGGAACACGCTGCAGCTCAATGCCGCGCGCAAAACGCTAGCGCTGCACGACAATCTCCTGCGGCGGCGGCTCATCGATACCTACGAGCGCGGCGATCTCGGCTACGTCAGCGTGCTGATGGCGGCGAAATCGTTCTCGGATTTCGTAGAACGCTGGCAAGACTTGGGTCTGCTGATCGCGGCCAATCAGCGTGCCGTGCGCGAACGCAGGGCCGCCGCGAAAAAAGTGGCGGTCGCGCAACAAAATCTGCAAGCCACTCAAGCGATACTCGAGCAGCAACAGCTGGCGCAGCAGCGCGCGAAAAATCAGCTCGACACGCTCGCACAGGAACGCGGGAACCTCGTGGCCCTGGCGGATGCGCAACGCCATCACGTGGCCGGACAAGTCGCCGAGATGGAGGGCCTGAGCGAAGCCGAAAACGCGCAGCTCGAAGCGCTGATCCGC'

In [220]:
def cosine_distance(x, y):
    xy = x.dot(y.T)
    dist = xy/(norm(x)*norm(y))
    return 1-dist[0,0]

test9_tf_idf = corpus[9,:]
test18_tf_idf = corpus[1,:]

print '================= Cosine distance from test9'
print 'test9 - {0:24s}: {1:f}'.format('test18',
                                             cosine_distance(test9_tf_idf, test18_tf_idf))


================= Cosine distance from test9
test9 - test18                  : 0.871986


In [226]:
from itertools import combinations

In [227]:
def search_nearby_bins(query_bin_bits, table, search_radius=2, initial_candidates=set()):
    """
    For a given query vector and trained LSH model, return all candidate neighbors for
    the query among all bins within the given search radius.
    
    Example usage
    -------------
    >>> model = train_lsh(corpus, num_vector=16, seed=143)
    >>> q = model['bin_index_bits'][0]  # vector for the first document
  
    >>> candidates = search_nearby_bins(q, model['table'])
    """
    num_vector = len(query_bin_bits)
    powers_of_two = 1 << np.arange(num_vector-1, -1, -1)
    
    # Allow the user to provide an initial set of candidates.
    candidate_set = copy(initial_candidates)
    candidate_set.update(table[query_bin_bits.dot(powers_of_two)])
    
    for different_bits in combinations(range(num_vector), search_radius):       
        # Flip the bits (n_1,n_2,...,n_r) of the query bin to produce a new bit vector.
        ## Hint: you can iterate over a tuple like a list
        alternate_bits = copy(query_bin_bits)
        for i in different_bits:
            alternate_bits[i] = int(not alternate_bits[i]) # YOUR CODE HERE 
        
        
        # Convert the new bit vector to an integer index
        nearby_bin = alternate_bits.dot(powers_of_two)
        #print nearby_bin
        # Fetch the list of documents belonging to the bin indexed by the new bit vector.
        # Then add those documents to candidate_set
        # Make sure that the bin exists in the table!
        # Hint: update() method for sets lets you add an entire list to the set
        if nearby_bin in table:
            candidate_set.update(table[nearby_bin]) # YOUR CODE HERE: Update candidate_set with the documents in this bin.
    #print candidate_set        
    return candidate_set

In [228]:
def query(vec, model, k, max_search_radius):
  
    data = model['data']
    table = model['table']
    random_vectors = model['random_vectors']
    num_vector = random_vectors.shape[1]
    
    
    # Compute bin index for the query vector, in bit representation.
    bin_index_bits = (vec.dot(random_vectors) >= 0).flatten()
    
    # Search nearby bins and collect candidates
    candidate_set = set()
    for search_radius in xrange(max_search_radius+1):
        candidate_set = search_nearby_bins(bin_index_bits, table, search_radius, initial_candidates=candidate_set)
    
    # Sort candidates by their true distances from the query
    nearest_neighbors = graphlab.SFrame({'id':candidate_set})
    candidates = data[np.array(list(candidate_set)),:]
    nearest_neighbors['distance'] = pairwise_distances(candidates, vec, metric='cosine').flatten()
    
    return nearest_neighbors.topk('distance', k, reverse=True), len(candidate_set)

In [233]:
query(corpus[9,:], model, k=10, max_search_radius=4)

(Columns:
 	id	int
 	distance	float
 
 Rows: 10
 
 Data:
 +------+----------------+
 |  id  |    distance    |
 +------+----------------+
 |  9   |      0.0       |
 | 189  | 0.684819148479 |
 | 1148 | 0.686114027217 |
 | 1898 | 0.71005570113  |
 | 781  | 0.719244671409 |
 | 1061 | 0.720765348181 |
 | 635  | 0.725095218772 |
 | 800  | 0.725971411356 |
 | 631  | 0.726437072805 |
 | 1347 | 0.726812784925 |
 +------+----------------+
 [10 rows x 2 columns], 1584)

In [234]:
gl_dna[9]['Sequence']

'CGAGCGCCGAACGAGCGACGCGTTCGGCGTGAAAGAACTTTCTGCCGTTTTGATCGGTCAGCGCGAAGTGCGCGGCATAGACCTGGTCGCCGCGCCACCGGCTGCCCCCGAGAATCCGCCTGGCGCGCGCGACGTCCTGGGGCCGTACGCGTGCGCGAAAGAACGTGACTTCGTAACCGAAGCGGCGCCCGTCGGCCGCTTTGAGGTGCCCGGTAAAATACCACCATTCGCTTTGGTAATTCGGGTGCGAGCCATGGTCGGCCGGAAAATGGAATTGATACGGCGCGGTTGCGATCGCGAATGCGGCCGCGGCGGCGATCAAGAGTTTCATTCGGTTCGCACGGCATCAGCCGTTGCGATGCGCGCGGCGACACTTGCCGGATAGAGTCCGGCCAGAATGGCCGCAGCGAGGACGAGGAGCAGCGATTCCGCCAGCGGCCAGTACGGCACGTGCAGATGCATGGGCCACCCGAAGGCTTGACGATCGATGACGTAGATCAGCAGCAACCCCAACAACATTCCCGCACCTATTCCGAACAAACCGCCCAGAATCCCGATCAGGGTGGCTTCGTAGAGCACCATATTTCGAACCGAACGGATCGTCAACCCCAGATAACGCAAGACGCCGATCTCCCGGCGGCGTTCCAGGACGAGCGCGAAGAGCGTGCTTACGACGCCCATGACGGCGATCGTAATCGCGATAATGTTGAGTGCCTGCGTAATGAGAAAAGTGCGATCGAAGATGGCGAAAACGACCGCGCGCAGGTCGTGCGTGCTCTGCACTTCGACGCGTAGCGGCAGCGCCGCGCGAATCACTCGTGTGCGCAGCGCGTTGAGATCCGTGCCGGGTTTGGCGTAGACGGAAAACATGCCGGCGGAGTCGTCGTGATAAAGACGGTTAAACGTACGCTGGTCGACCAAAACGGTGCCCGAATCATTCGAGTAATCATCATAAATGGCCGCGATGGCGAACGAGAGGGGCCCGGCCGGCGTGTCGAG

In [235]:
gl_dna[189]['Sequence']

'AGCGAACGCGCTGTCGTCGAACGCTTGCGCGCTGATTTTCCCCACGCTGCCTTTCTGGGAGAAGAAGGCGGACTGCAGTCCGGCACGTCGCGCGAGCGGTGGATTATCGACCCGCTGGACGGCACCACGAATTACGCACACGGCTATCCGATTTTTTGCGTCTCGATTGCGTTCGAGCGCGATGGCGAGGTCGTGGCCGCCGTCGTGCACGCGCCGGCGATGCACGAAACATTCGTCGCCGAGCGCAGAGGTGGCGCGACGCTGAACGATCGCGCTATCGCGGTCTCGAGAATCGAGAGTTTATCCGCGTCGCTGGTCTGCACCGGCTTCCAGCCGGCGCGCTACGAGCGCAACATGCGCTATTTCGACGCCGCTTCGCAGATGACGCAAGGCGTGCGCCGAGACGGTTCGGCCGCACTCAATCTCGCGTACGTAGCATGCGGCCGCTTCGATGTGTTTTGGGAGTTCGATTTGCACCAATGGGATACGGCGGCTGGTTCGCTGCTCGTACGTGAAGCCGGCGGCCGCGTCACGACGATTGAAGGAACGGATTGGACGCTCGAAAGCGCGTCGGTTCTGGCGAGCAATGGCGCCGTTCACGACGAATCGTTAGAGCTCTTTACGCGTTTGCGCTAACCCGCCGCGATCAGCTCGCGCCGTGTCCAACTTTCGCCGCGCACTTTTATCGCGGTCGCGACGGCGCGCGCACTCCAGGCGACGATCCACGCAACCGGCACACCGTACAACCCGATGTGCAGAACTTTGATGCAGAGATAGCAGACCGGAACGACGAGAACTCCGGTGAGTATTCCGACCGTCAGCGAAAAGCGCGTATCTCCCGACGCGCGGATCGGCGACATCGATACCATCGCGTAGCCTTTGAGCGGAAGTGTCAGCATGTGCAGCGCGAGCGGCCAGGCCGCGACCGTCGCGACGACGGCGTTCAGCGTAAAGATAAAGGCCAGCGGCCATGCCAGCAAAGCGCAGACGGGGCCGGTC

In [236]:
gl_dna[1148]['Sequence']

'AGATTGCGTAGCGCCGTCACGTGCAGCTGCGAAGCGCGCTGCGGCGAAATGGCAAGCACGCGTCCTATCTCGTAGAGCGACTTGTTGGAATAATAGTAGAGCGTCACGACGCTGCGCTGGCGGCGCGTCAGCTTCATGAGCGCGTTTTGAATGTACTCGCGATGGAATGTCTTGCCGGCCAGCTGTGCCGGATCTTGCGTCCAATCCGGCTGCAGCGATTCATCGGCCGGCAACGGCGAATCCAGCGAGAGCGGCGCATACCGGTAGGCGTGCAGCGCCGCGCGCCGCAGCGACGGCCTCCGCATCTCCATCTCGCTCTGCGTCGGAATCACGCCGCTGTCGAGCGCGAGCGCGTAACGTTCGCGTTCGGCCTCGCGCACCTCGCGGCGAACGCGTTCCGAGACCGGATCGAGCCGGCGCAAACCGTTGAGCATTGTACCGGCGACGACACGCGAGACGTAGACGCGCATCTCTGGTCCGCGCTGCGGATCGAAGGCATCCACTGCGCGAATCAGACCGACGCAGCCGTCTCCGATCAAGTCATCGAGATCGCTTCCCGGCACCATGCGCTGAATGCGGCGCGCGATGCTCCGCACCAGCGGAAAGTACGAACGGATCAACGTTTCGCGGGCGCTCACGGCGAAAGGCGCGACGCGATCTTCTCGGCGCACGCTTCGGCGACGAGCTCCCCGAATTCGCCCATCGCCTCGGCGAGCGGCACCAGCACGCCTTCCAGGACCGGCTCGAGCGCAAGCGCCGCGATCTGCCGCTGCGCGAGGGGGTTTTCAATCACGGCTCAGATTGTCGGCGATGCGCATCATCTCGTCGGCGGCCTGCACGCCCTTGGCGTTGGCTTCGTACGCGCGCTGCGCAGCGAGAATCTGCATCATCGCCTCGACGATGGTGACGTTGGATCGTTCGAGCATGCCGAACTTCAGCTCGGGACCGCCGTGCTTGCCGGGATCGATGAACCGCGCTTTTCCGGACGCCTTCGTTTCG